config/routes.rb
Rails.application.routes.draw do
  get 'login' ,to: 'main#login'
  post 'main/create'
  get 'main/destroy'
  get 'main' ,to: 'main#home'
  get 'profile' ,to: 'main#profile'
  get 'my_market' ,to: 'main#market'
  get 'purchase_history' ,to: 'main#history'
  get 'sale_history' ,to: 'main#history'
  get 'my_inventory' ,to: 'main#inventory'
  get 'top_seller' ,to: 'main#topseller'
  post 'create_tables' ,to: 'main#create_tables'
  post 'buy' ,to: 'main#buy'
  resources :markets
  resources :inventories
  resources :items
  resources :users
  get 'changepassword', to: 'users#changePassword'
  post 'newpassword', to: 'users#newPassword'
  post 'updateinventory', to: 'markets#updateInventory'
  post 'addmarket', to: 'markets#addMarket'
  post 'search' ,to: 'main#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  $startDate = ''
  $finalDate = ''

  def login
    # is_login? if login already cant login again until logout 
    login_again?
  end

  def create
    # check overlap login?
    if is_login?
      redirect_to main_path, notice: 'Please logout your account before login again!'
    else
      # check login authenticate with password?
      u = User.where(email: params[:email]).first
      if u and u.authenticate(params[:password])
        redirect_to main_path
        session[:id] = u.id
        session[:logged_in] = true
      else
        redirect_to login_path, notice: 'your username or your password is wrong. please try again!'
      end
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'logout already!'
  end

  def home
    if session[:logged_in]
      @role = role?
      @id = session[:id]
      session[:create] = false
      session[:search] = false
    else
      @role = 'guest'
    end
    
  end

  def profile
    must_be_logged_in
    redirect_to "/users/" + session[:id].to_s
  end

  def market
    if session[:logged_in]
      @role = role?
    else
      @role = 'guest'
    end
  end

  def history
    must_be_logged_in
    u = User.where(id: session[:id]).first
    if u and ((u.user_type == 0) or (u.user_type == 2))
      @history = Inventory.where(user_id: session[:id]).order(:created_at)
      render "purchase"
    elsif u and (u.user_type == 1)
      @history = Inventory.where(seller_id: session[:id]).order(:created_at)
      render "sale"
    end
  end

  def inventory
    must_be_logged_in
    @inven = Market.where(user_id: session[:id])
    @items = Item.where(enable: true)
    render "my_inventory"
  end

  def topseller
    must_be_logged_in
    if session[:create]
      @startDate = $startDate
      @finalDate = $finalDate
    end
  end

  def create_tables
    $startDate = params[:startdate]
    $finalDate = params[:finaldate]
    session[:create] = true
    redirect_to top_seller_path
  end

  def buy
    @amount = params[:amount].to_i
    $m = Market.where(id: params[:f_id]).first
    $I = Inventory.new
    a = params[:amount_check]
    if a.to_i == $m.quantity
      if @amount > $m.quantity
        redirect_to my_market_path , notice: "the quantity of this goods is not enough"
      else
        $m.quantity -= @amount
        $m.save
        $I.user_id = session[:id].to_i
        $I.item_id = $m.item_id
        $I.seller_id = $m.user_id
        $I.price = $m.price
        $I.quantity = @amount
        $I.save
        redirect_to my_market_path , notice: "transaction success"
      end
    else
      redirect_to my_market_path , notice: "Information need to be updated before editted"
    end
  end

  def search
    session[:regx] = "/" + params[:search] + "/"
    session[:search] = true
    redirect_to my_market_path
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/create.html.erb
<h1>Main#create</h1>
<p>Find me in app/views/main/create.html.erb</p>

app/views/main/destroy.html.erb
<h1>Main#destroy</h1>
<p>Find me in app/views/main/destroy.html.erb</p>

app/views/main/home.html.erb
<h1>Home</h1>
<p>Welcome to RubyOnHell Store : id <%=@id%></p>

<%# everyone who already login can open this page %>
<% if @role == 'admin' or @role == 'seller' or @role == 'buyer'%>
    <%= link_to "Profile" , profile_path %>
    <%= link_to "Logout" , main_destroy_path%>
<%end%>

<%# seller and admin can open this page %>
<% if @role == 'admin' or @role == 'seller'%>
    <%= link_to "Sale History" , sale_history_path %>
    <%= link_to "My Inventory" , my_inventory_path %>
    <%= link_to "Top Seller" , top_seller_path %>
<%end%>

<%# buyer and admin can open this page %>
<% if @role == 'admin' or @role == 'buyer'%>
    <%= link_to "My Market" , my_market_path %>
    <%= link_to "Purchase History" , purchase_history_path %>
<%end%>

<% if @role == 'guest'%>
    <%= link_to "My Market" , my_market_path %>
    <%= link_to "LogIn" , login_path %>
<%end%>

app/views/main/inventory.html.erb
<h1>Main#inventory</h1>
<p>Find me in app/views/main/inventory.html.erb</p>

app/views/main/login.html.erb
<%= form_with url: main_create_path, method: :post , data: {turbo: false} do |f| %>
    <div>
        <%=f.label :email, "Email"%> 
        <%=f.text_field :email%>
    </div>
    <div>
        <%=f.label :login, "password"%> 
        <%=f.password_field :password%>
    </div>
   <%=f.submit :OK %>
   <%= link_to "back to main" , main_path%>
<% end %>

app/views/main/market.html.erb
<h1>My_Market</h1>
<%= link_to "back to main" , main_path%>
<%= form_with url: search_path, method: :post , data: {turbo: false} do |f| %>
    <%=f.label :name , "Category Search"%>
    <%=f.text_field :search%>
    <%=f.submit :search %>
<%end%>
<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Name Item</th>
            <th>Category</th>
            <th>Name Seller</th>
            <th>Price</th>
            <th>Quantity</th>
            <%if @role != 'guest'%>
                <th>amount</th>
                <th>Buy</th>
            <% end %>
        </tr>
    </thead>
    
    
    <tbody>
    <% if session[:search]%>
        <% reg = Regexp.new(session[:regx])%>
    <%end%>
    <% $u = Market.all%>
    <% for e in $u do%>
        <% x = User.where(id: e.user_id).first%>
        <% y = Item.where(id: e.item_id).first%>
            <tr>
                <td><%=y.name%></td>
                <td><%=y.category%></td>
                <td><%=x.name%></td>
                <td><%=e.price%></td>
                <td><%=e.quantity%></td>
                <%if @role != 'guest'%>
                    <%= form_with url: buy_path, method: :post , data: {turbo: false} do |f| %>
                        <%=f.hidden_field :amount_check , value: e.quantity%>
                        <%=f.hidden_field :f_id , value: e.id%>
                        <td><%=f.number_field :amount , in: 1..1000000, step: 1%></td>
                        <td><%=f.submit :Buy %></td>
                    <%end%>
                <% end %>  
            </tr>
        
    <%end%>
    </tbody>
</table>
<% session[:search] = false%>
<script type="text/javascript" class="init">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

app/views/main/my_inventory.html.erb
<h1>My inventory</h1>
<%session[:back] = "my_inventory"%>
<table class="display" style="width:100%">
    <thead>
        <tr>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>save</th>
            <th>delete</th>
        </tr>
    </thead>
    <tbody>
        <% @inven.each do |i| %>
        <% item_name = Item.where(id: i.item_id).first.name%>
        <% url = "/updateinventory"%>
        <%= form_with url: url, method: :post , data: {turbo: false} do |f| %>
        <%=f.hidden_field :market_id, value: i.id%>
        <%=f.hidden_field :price_check, value: i.price%>
        <%=f.hidden_field :quantity_check, value: i.quantity%>
        <tr>
            <td><%=item_name%></td>
            <td><%=f.text_field :price, value: i.price%></td>
            <td><%=f.text_field :quantity, value: i.quantity%></td>
            <td><%=f.submit :save %></td>
            <%end%>
            <td> <%= button_to "Delete", i, method: :delete %></td>
        </tr>
        <%end%>
        
        <% addurl = "/addmarket"%>
        <%= form_with url: addurl, method: :post , data: {turbo: false} do |f| %>
        <%=f.hidden_field :user_id, value: session[:id]%>
        <tr>
            <td><%= f.select :item_id, @items.map{|i| [i.name, i.id]}, value: "please select"%></td>
            <td><%=f.text_field :price %></td>
            <td><%=f.text_field :quantity%></td>
            <td><%= f.submit :add %></td>   
        <% end %>
    </tr>
        
    </tbody>
</table>
<%= link_to "back to main" , main_path%>

app/views/main/phistory.html.erb
<h1>Main#phistory</h1>
<p>Find me in app/views/main/phistory.html.erb</p>

app/views/main/profile.html.erb
<h1>Main#profile</h1>
<p>Find me in app/views/main/profile.html.erb</p>

app/views/main/purchase.html.erb
<h1>Purchase history</h1>
<%= link_to "back to main" , main_path%>
<table class="display" style="width:100%">
    <thead>
        <tr>
            <th>Item</th>
            <th>Seller</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>date</th>
        </tr>
    </thead>
    <tbody>
        <% @history.each do |his| %>
        <% item_name = Item.where(id: his.item_id).first.name%>
        <% seller_name = User.where(id: his.seller_id).first.name%>
        <tr>
            <td><%=item_name%></td>
            <td><%=seller_name%></td>
            <td><%=his.price%></td>
            <td><%=his.quantity%></td>
            <td><%=his.created_at%></td>
        </tr>
        <%end%>
    </tbody>
</table>
<script type="text/javascript" class="init">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

app/views/main/sale.html.erb
<h1>Sale history</h1>
<%= link_to "back to main" , main_path%>
<table class="display" style="width:100%">
    <thead>
        <tr>
            <th>Item</th>
            <th>Buyer</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>date</th>
        </tr>
    </thead>
    <tbody>
        <% @history.each do |his| %>
        <% item_name = Item.where(id: his.item_id).first.name%>
        <% buyer_name = User.where(id: his.user_id).first.name%>
        <tr>
            <td><%=item_name%></td>
            <td><%=buyer_name%></td>
            <td><%=his.price%></td>
            <td><%=his.quantity%></td>
            <td><%=his.created_at%></td>
        </tr>
        <%end%>
    </tbody>
</table>
<script type="text/javascript" class="init">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

app/views/main/shistory.html.erb
<h1>Main#shistory</h1>
<p>Find me in app/views/main/shistory.html.erb</p>

app/views/main/topseller.html.erb
<h3>Top Seller</h3>
<%= link_to "back to main" , main_path%>
<%= form_with url: create_tables_path, method: :post , data: {turbo: false} do |f| %>
    <p>date</p>
    <%=f.datetime_field :startdate%>
    <%=f.datetime_field :finaldate%>
    <%=f.submit :Search %>
<%end%>

<%if session[:create]%>
    <%$x = Inventory.where(created_at: @startDate..@Finaldate)%>
    <%$total = Inventory.where(created_at: @startDate..@Finaldate).select("seller_id, item_id, sum(price * quantity) as total_price").group("item_id").order("total_price DESC")%>
    <%$amount = Inventory.where(created_at: @startDate..@Finaldate).select("seller_id, item_id, sum(quantity) as total_amount").group("item_id").order("total_amount DESC")%>
    <%if $total.first != nil%>
    <table>
        <thead>
            <tr>
                <th>Best Seller</th>
                <th>Item</th>
                <th>Best Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <% $total = $total.first%>
                <th><%=User.where(id: $total.seller_id).first.name%></th>
                <th><%=Item.where(id: $total.item_id).first.name%></th>
                <th><%=$total.total_price%></th>
            </tr>
        </tbody>
    </table>
    <%else%>
        <p>No one is seller that has best price in your date range</p>
    <%end%>
    <%if $amount.first != nil%>
    <table>
        <thead>
            <tr>
                <th>Best Seller</th>
                <th>Item</th>
                <th>Best Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <%$amount = $amount.first%>
                <th><%=User.where(id: $amount.seller_id).first.name%></th>
                <th><%=Item.where(id: $amount.item_id).first.name%></th>
                <th><%=$amount.total_amount%></th>
            </tr>
        </tbody>
    </table>
    <%else%>
        <p>No one is seller that has best amount of quantity in your date range</p>
    <%end%>
    <% session[:create] = false%>
<%end%>