config/routes.rb
Rails.application.routes.draw do
  get 'login' ,to: 'main#login'
  post 'main/create'
  get 'main/destroy'
  get 'main' ,to: 'main#home'
  get 'profile' ,to: 'main#profile'
  get 'my_market' ,to: 'main#market'
  get 'purchase_history' ,to: 'main#history'
  get 'sale_history' ,to: 'main#history'
  get 'my_inventory' ,to: 'main#inventory'
  get 'top_seller' ,to: 'main#topseller'
  post 'create_tables' ,to: 'main#create_tables'
  post 'buy' ,to: 'main#buy'
  resources :markets
  resources :inventories
  resources :items
  resources :users
  get 'changepassword', to: 'users#changePassword'
  post 'newpassword', to: 'users#newPassword'
  post 'updateinventory', to: 'markets#updateInventory'
  post 'addmarket', to: 'markets#addMarket'
  post 'search' ,to: 'main#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def changePassword
    render "changepassword"
  end

  def newPassword
    u = User.where(id: session[:id]).first
    if u and u.authenticate(params[:password])
      if params[:newPassword] and (params[:newPassword] == params[:confirmPassword])
        u.password = params[:newPassword]
        u.save
        url = "/users/" + session[:id].to_s
        redirect_to url, notice: "Your new password already saved."
      else
        redirect_to changepassword_path, notice: "Your new password not matched."
      end
    else
      redirect_to changepassword_path, notice: "Your password is not correct."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :name, :user_type, :lock_version)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= form.hidden_field :lock_version%>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>User type:</strong>
    <% role = "admin"%>
    <% if user.user_type == 1%>
    <% role = "seller"%>
    <% elsif user.user_type == 2%>
    <% role = "buyer"%>
    <%end%>
    <%= role %>
  </p>

</div>

app/views/users/changepassword.html.erb
<%= form_with url: newpassword_path , method: :post , data: {turbo: false} do |f| %>
    <div>
        <%= f.label :password, "current password"%>
        <%= f.text_field :password%>
    </div>
    <div>
        <%= f.label :newPassword, "new password"%>
        <%= f.text_field :newPassword%>
    </div>
    <div>
        <%= f.label :confirmPassword, "confirm new password"%>
        <%= f.text_field :confirmPassword%>
    </div>
    <div>
        <%= f.submit :confirm%>
    </div>

<%end%>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %> |
  <%= link_to "change password", "/changepassword" %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>